/*
 * pictic API
 * The website is pictic, a web-based platform that offers image hosting and sharing services. Users can upload their own images and view a feed of user-generated image posts. The platform is designed to integrate Machine Learning (ML) algorithms for automatic image labeling, improving the searchability and discoverability of content on the platform. Users can interact with posts by upvoting, and commenting on them. The website features a simple and easy-to-use interface with tools such as tagging, liking, and commenting to help users organize and share their content. The website also offers features such as profile customization, search functionality, and a Chart-topping page displaying posts in order of upvotes.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.31
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PicticApi);
  }
}(this, function(expect, PicticApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PicticApi.ImageApi();
  });

  describe('(package)', function() {
    describe('ImageApi', function() {
      describe('deleteImage', function() {
        it('should call deleteImage successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteImage call
          /*
          var id = 789;
          var opts = {};
          opts.apiKey = "apiKey_example";

          instance.deleteImage(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('findImagesByTags', function() {
        it('should call findImagesByTags successfully', function(done) {
          // TODO: uncomment, update parameter values for findImagesByTags call and complete the assertions
          /*
          var opts = {};
          opts.tags = "tags_example";

          instance.findImagesByTags(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PicticApi.Image);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.title).to.be.a('string');
            expect(data.title).to.be("");
            expect(data.tags).to.be.a('string');
            expect(data.tags).to.be("");
            expect(data.url).to.be.a('string');
            expect(data.url).to.be("");
            expect(data.upvotes).to.be.a('number');
            expect(data.upvotes).to.be(0);
            {
              let dataCtr = data.comments;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(PicticApi.Comment);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be("0");
                expect(data.username).to.be.a('string');
                expect(data.username).to.be("");
                expect(data.text).to.be.a('string');
                expect(data.text).to.be("");

                      }
            }
            expect(data.ceatedByUserId).to.be.a('number');
            expect(data.ceatedByUserId).to.be(0);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('findImagesByitle', function() {
        it('should call findImagesByitle successfully', function(done) {
          // TODO: uncomment, update parameter values for findImagesByitle call and complete the assertions
          /*
          var opts = {};
          opts.title = "title_example";

          instance.findImagesByitle(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PicticApi.Image);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.title).to.be.a('string');
            expect(data.title).to.be("");
            expect(data.tags).to.be.a('string');
            expect(data.tags).to.be("");
            expect(data.url).to.be.a('string');
            expect(data.url).to.be("");
            expect(data.upvotes).to.be.a('number');
            expect(data.upvotes).to.be(0);
            {
              let dataCtr = data.comments;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(PicticApi.Comment);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be("0");
                expect(data.username).to.be.a('string');
                expect(data.username).to.be("");
                expect(data.text).to.be.a('string');
                expect(data.text).to.be("");

                      }
            }
            expect(data.ceatedByUserId).to.be.a('number');
            expect(data.ceatedByUserId).to.be(0);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('imagesIdGet', function() {
        it('should call imagesIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for imagesIdGet call and complete the assertions
          /*
          var id = 789;

          instance.imagesIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PicticApi.Image);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.title).to.be.a('string');
            expect(data.title).to.be("");
            expect(data.tags).to.be.a('string');
            expect(data.tags).to.be("");
            expect(data.url).to.be.a('string');
            expect(data.url).to.be("");
            expect(data.upvotes).to.be.a('number');
            expect(data.upvotes).to.be(0);
            {
              let dataCtr = data.comments;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(PicticApi.Comment);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be("0");
                expect(data.username).to.be.a('string');
                expect(data.username).to.be("");
                expect(data.text).to.be.a('string');
                expect(data.text).to.be("");

                      }
            }
            expect(data.ceatedByUserId).to.be.a('number');
            expect(data.ceatedByUserId).to.be(0);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('imagesIdSharePost', function() {
        it('should call imagesIdSharePost successfully', function(done) {
          // TODO: uncomment, update parameter values for imagesIdSharePost call and complete the assertions
          /*
          var id = 789;

          instance.imagesIdSharePost(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PicticApi.InlineResponse200);
            expect(data.link).to.be.a('string');
            expect(data.link).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('imagesIdUpvotePost', function() {
        it('should call imagesIdUpvotePost successfully', function(done) {
          // TODO: uncomment, update parameter values for imagesIdUpvotePost call and complete the assertions
          /*
          var id = 789;

          instance.imagesIdUpvotePost(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PicticApi.Image);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.title).to.be.a('string');
            expect(data.title).to.be("");
            expect(data.tags).to.be.a('string');
            expect(data.tags).to.be("");
            expect(data.url).to.be.a('string');
            expect(data.url).to.be("");
            expect(data.upvotes).to.be.a('number');
            expect(data.upvotes).to.be(0);
            {
              let dataCtr = data.comments;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(PicticApi.Comment);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be("0");
                expect(data.username).to.be.a('string');
                expect(data.username).to.be("");
                expect(data.text).to.be.a('string');
                expect(data.text).to.be("");

                      }
            }
            expect(data.ceatedByUserId).to.be.a('number');
            expect(data.ceatedByUserId).to.be(0);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('imagesPost', function() {
        it('should call imagesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for imagesPost call and complete the assertions
          /*
          var title = "title_example";
          var image = "/path/to/file.txt";
          var opts = {};
          opts.createdByUserId = 56;

          instance.imagesPost(title, image, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PicticApi.Image);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.title).to.be.a('string');
            expect(data.title).to.be("");
            expect(data.tags).to.be.a('string');
            expect(data.tags).to.be("");
            expect(data.url).to.be.a('string');
            expect(data.url).to.be("");
            expect(data.upvotes).to.be.a('number');
            expect(data.upvotes).to.be(0);
            {
              let dataCtr = data.comments;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(PicticApi.Comment);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be("0");
                expect(data.username).to.be.a('string');
                expect(data.username).to.be("");
                expect(data.text).to.be.a('string');
                expect(data.text).to.be("");

                      }
            }
            expect(data.ceatedByUserId).to.be.a('number');
            expect(data.ceatedByUserId).to.be(0);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
