# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, link: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param link: The link of this InlineResponse200.  # noqa: E501
        :type link: str
        """
        self.swagger_types = {
            'link': str
        }

        self.attribute_map = {
            'link': 'link'
        }

        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def link(self) -> str:
        """Gets the link of this InlineResponse200.

        Shareable link to the image  # noqa: E501

        :return: The link of this InlineResponse200.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link: str):
        """Sets the link of this InlineResponse200.

        Shareable link to the image  # noqa: E501

        :param link: The link of this InlineResponse200.
        :type link: str
        """

        self._link = link
