# coding: utf-8

"""
    pictic API

    The website is pictic, a web-based platform that offers image hosting and sharing services. Users can upload their own images and view a feed of user-generated image posts. The platform is designed to integrate Machine Learning (ML) algorithms for automatic image labeling, improving the searchability and discoverability of content on the platform. Users can interact with posts by upvoting, and commenting on them. The website features a simple and easy-to-use interface with tools such as tagging, liking, and commenting to help users organize and share their content. The website also offers features such as profile customization, search functionality, and a Chart-topping page displaying posts in order of upvotes.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.image_api import ImageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestImageApi(unittest.TestCase):
    """ImageApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.image_api.ImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_image(self):
        """Test case for delete_image

        Deletes an image  # noqa: E501
        """
        pass

    def test_find_images_by_tags(self):
        """Test case for find_images_by_tags

        Finds images by tags  # noqa: E501
        """
        pass

    def test_find_images_byitle(self):
        """Test case for find_images_byitle

        Finds images by title  # noqa: E501
        """
        pass

    def test_images_id_get(self):
        """Test case for images_id_get

        Get a specific image by ID  # noqa: E501
        """
        pass

    def test_images_id_share_post(self):
        """Test case for images_id_share_post

        Get a shareable link to an image  # noqa: E501
        """
        pass

    def test_images_id_upvote_post(self):
        """Test case for images_id_upvote_post

        Upvote an image  # noqa: E501
        """
        pass

    def test_images_post(self):
        """Test case for images_post

        Upload a new image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
