# coding: utf-8

"""
    pictic API

    The website is pictic, a web-based platform that offers image hosting and sharing services. Users can upload their own images and view a feed of user-generated image posts. The platform is designed to integrate Machine Learning (ML) algorithms for automatic image labeling, improving the searchability and discoverability of content on the platform. Users can interact with posts by upvoting, and commenting on them. The website features a simple and easy-to-use interface with tools such as tagging, liking, and commenting to help users organize and share their content. The website also offers features such as profile customization, search functionality, and a Chart-topping page displaying posts in order of upvotes.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.comment_api import CommentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommentApi(unittest.TestCase):
    """CommentApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.comment_api.CommentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_comment(self):
        """Test case for delete_comment

        Deletes a comment  # noqa: E501
        """
        pass

    def test_images_id_comments_post(self):
        """Test case for images_id_comments_post

        Add a comment to an image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
